#!/bin/sh
#
# @name NXP HoverGames
#
# @type Quadrotor x
# @class Copter
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#
# @maintainer Iain Galloway <iain.galloway@nxp.com>
#

. ${R}etc/init.d/rc.mc_defaults
. ${R}etc/init.d/rc.quad_x_default_geometry

param set-default IMU_DGYRO_CUTOFF 20

param set-default MC_ROLLRATE_P 0.18
param set-default MC_ROLLRATE_I 0.15

param set-default MC_PITCHRATE_P 0.18
param set-default MC_PITCHRATE_I 0.15
